### ISSUE TITLE
SLIP function on VINYL/SLIP button

### ISSUE THREAD

**Issue by ViStefan** [julia-otran/Mixxx-Pioneer-DDJ-SB3#3]
Hi! I wrote you on e-mail before issues were enabled!

Feature from topic is not implemented.
Will you have a time soon to do that? If no, I will try by myself.

Again, thank you for your great job!

**Comment by julia-otran** [comment]
Closed by https://github.com/julia-otran/Mixxx-Pioneer-DDJ-SB3/pull/4

**Comment by julia-otran** [comment]
If something is not working as excpected, comment here and i will reopen this issue.

Also, be sure to update the files according to the installation guide, (or, at least ensure to update the mappings because they changed)
